# Generated by Django 5.0.6 on 2024-06-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('inbid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
                ('date_received', models.DateTimeField()),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('outid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
                ('date_shipped', models.DateTimeField()),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artiseliteApp.location')),
                ('supplierid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artiseliteApp.supplier')),
            ],
        ),
    ]
